INSERT INTO `kode_kantors` (`id`, `kode_kantor`, `kode_kantor_slik`, `nama_kantor`, `created_at`, `updated_at`) VALUES (1, '001', '000', 'pusat', NULL, NULL);
INSERT INTO `kode_kantors` (`id`, `kode_kantor`, `kode_kantor_slik`, `nama_kantor`, `created_at`, `updated_at`) VALUES (2, '002', '002', 'cab. cisalak', NULL, NULL);
INSERT INTO `kode_kantors` (`id`, `kode_kantor`, `kode_kantor_slik`, `nama_kantor`, `created_at`, `updated_at`) VALUES (3, '003', '001', 'cab. kpo', NULL, NULL);
INSERT INTO `kode_kantors` (`id`, `kode_kantor`, `kode_kantor_slik`, `nama_kantor`, `created_at`, `updated_at`) VALUES (4, '004', '003', 'cab. subang', NULL, '2024-06-05 10:54:35');
INSERT INTO `kode_kantors` (`id`, `kode_kantor`, `kode_kantor_slik`, `nama_kantor`, `created_at`, `updated_at`) VALUES (5, '005', '004', 'cab. purwadadi', NULL, '2024-06-05 10:54:41');
INSERT INTO `kode_kantors` (`id`, `kode_kantor`, `kode_kantor_slik`, `nama_kantor`, `created_at`, `updated_at`) VALUES (6, '006', '005', 'cab. pamanukan', '2024-06-05 10:55:09', '2024-06-05 10:55:09');
INSERT INTO `kode_kantors` (`id`, `kode_kantor`, `kode_kantor_slik`, `nama_kantor`, `created_at`, `updated_at`) VALUES (7, '007', '007', 'cab. majalengka', NULL, NULL);
INSERT INTO `kode_kantors` (`id`, `kode_kantor`, `kode_kantor_slik`, `nama_kantor`, `created_at`, `updated_at`) VALUES (8, '008', '008', 'cab. panyingkiran', NULL, NULL);
INSERT INTO `kode_kantors` (`id`, `kode_kantor`, `kode_kantor_slik`, `nama_kantor`, `created_at`, `updated_at`) VALUES (9, '009', '009', 'cab. banjaran', NULL, NULL);
INSERT INTO `kode_kantors` (`id`, `kode_kantor`, `kode_kantor_slik`, `nama_kantor`, `created_at`, `updated_at`) VALUES (10, '010', '010', 'cab. cingambul', NULL, NULL);
INSERT INTO `kode_kantors` (`id`, `kode_kantor`, `kode_kantor_slik`, `nama_kantor`, `created_at`, `updated_at`) VALUES (11, '011', '011', 'cab. bekasi', NULL, NULL);
INSERT INTO `kode_kantors` (`id`, `kode_kantor`, `kode_kantor_slik`, `nama_kantor`, `created_at`, `updated_at`) VALUES (12, '012', '012', 'cab. pondok gede', NULL, NULL);
INSERT INTO `kode_kantors` (`id`, `kode_kantor`, `kode_kantor_slik`, `nama_kantor`, `created_at`, `updated_at`) VALUES (13, '013', '013', 'cab. cibitung', NULL, NULL);
INSERT INTO `kode_kantors` (`id`, `kode_kantor`, `kode_kantor_slik`, `nama_kantor`, `created_at`, `updated_at`) VALUES (14, '014', '014', 'cab. setu', NULL, NULL);
INSERT INTO `kode_kantors` (`id`, `kode_kantor`, `kode_kantor_slik`, `nama_kantor`, `created_at`, `updated_at`) VALUES (15, '015', '015', 'cab. cibarusah', NULL, NULL);
INSERT INTO `kode_kantors` (`id`, `kode_kantor`, `kode_kantor_slik`, `nama_kantor`, `created_at`, `updated_at`) VALUES (16, '016', '016', 'cab. sukatani', NULL, NULL);
INSERT INTO `kode_kantors` (`id`, `kode_kantor`, `kode_kantor_slik`, `nama_kantor`, `created_at`, `updated_at`) VALUES (17, '017', '017', 'cab. cimerak', NULL, NULL);
INSERT INTO `kode_kantors` (`id`, `kode_kantor`, `kode_kantor_slik`, `nama_kantor`, `created_at`, `updated_at`) VALUES (18, '018', '018', 'cab. ciamis', NULL, NULL);
